"""app settings, account import hint, rows skipped old

Revision ID: 9cec822a1a7c
Revises: a17e16b08b91
Create Date: 2026-09-28 02:40:10.547575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9cec822a1a7c'
down_revision: Union[str, None] = 'a17e16b08b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_hint', sa.String(length=100), nullable=True))

    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows_skipped_old', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_column('rows_skipped_old')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('import_hint')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
